export const DEFAULT_MATRIX_GRID_OPACITY = 0.5;
export const DEFAULT_MATRIX_GRID_WIDTH = 1;
export const DEFAULT_MATRIX_BG_OPACITY = 1;

export const MATRIX_BUFFER_ZONE_RATIO = 0.2;

export const NATIVE_RESOLUTION_W = 1280;
export const NATIVE_RESOLUTION_H = 720;
